weights: ../user_data/model_data/exp/weights/best.pt
cfg: ''
data: data/underwater.yaml
hyp: data/hyp.scratch.yaml
epochs: 150
batch_size: 8
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: true
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
log_artifacts: false
workers: 0
project: ../user_data/model_data/
name: exp
exist_ok: false
total_batch_size: 8
world_size: 1
global_rank: -1
save_dir: ..\user_data\model_data\exp
